"""Research report generator — produces a Markdown summary of the research process.

This is what the user (and interviewer) sees at the end of a run.
"""

from __future__ import annotations

import json
from datetime import datetime

from src.state import ResearchState
from src.tracker.comparison import compare_to_target
from src.tracker.db import ExperimentTracker


def generate_report(
    state: ResearchState,
    tracker: ExperimentTracker,
) -> str:
    """Generate a Markdown report of the entire research process.

    Args:
        state: Final research state after the loop ends
        tracker: ExperimentTracker with persisted data

    Returns:
        Markdown string suitable for display or saving
    """
    lines = [
        "# Research Report",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Repository:** {state.get('repo_url', 'N/A')}",
        f"**Verdict:** {state.get('verdict', 'unknown')}",
        f"**Rounds:** {state.get('round_number', 0)} / {state.get('max_rounds', 5)}",
        "",
        "---",
        "",
        "## Target Metrics",
        "",
    ]

    target = state.get("target_metrics", {})
    if target:
        lines.append("| Metric | Target |")
        lines.append("|--------|--------|")
        for k, v in target.items():
            lines.append(f"| {k} | {v} |")
    else:
        lines.append("(none specified)")
    lines.append("")

    # Best metrics achieved
    best = tracker.get_best_metrics()
    if best:
        lines.append("## Best Metrics Achieved")
        lines.append("")
        lines.append("| Metric | Achieved | Target | Gap |")
        lines.append("|--------|----------|--------|-----|")
        for metric, achieved in best.items():
            t = target.get(metric)
            gap = f"{abs(achieved - t):.4f}" if t else "-"
            lines.append(f"| {metric} | {achieved:.4f} | {t if t else '-'} | {gap} |")
        lines.append("")

    # Hypotheses
    hypotheses = state.get("hypotheses", [])
    if hypotheses:
        lines.append("## Hypotheses")
        lines.append("")
        lines.append("| Status | Statement | Confidence |")
        lines.append("|--------|-----------|------------|")
        for h in hypotheses:
            emoji = "✓" if h.status.value == "confirmed" else ("✗" if h.status.value == "rejected" else "○")
            lines.append(f"| {emoji} {h.status.value} | {h.statement[:80]} | {h.confidence:.0%} |")
        lines.append("")

    # Experiment history
    experiments = state.get("experiment_history", [])
    if experiments:
        lines.append("## Experiment History")
        lines.append("")
        lines.append("| Round | Action | Result |")
        lines.append("|-------|--------|--------|")
        for exp in experiments:
            lines.append(f"| {exp.round_number} | {exp.action[:60]} | {exp.observation[:80]} |")
        lines.append("")

    # Observations
    observations = state.get("observations", [])
    if observations:
        lines.append("## Key Observations")
        lines.append("")
        for obs in observations[-10:]:
            lines.append(f"- {obs[:200]}")
        lines.append("")

    # Final reflection
    reflection = state.get("reflection", "")
    if reflection:
        lines.append("## Final Reflection")
        lines.append("")
        try:
            ref = json.loads(reflection)
            for key, value in ref.items():
                lines.append(f"**{key}:** {value}")
                lines.append("")
        except (json.JSONDecodeError, AttributeError):
            lines.append(reflection)
        lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by Auto-Research Agent*")

    return "\n".join(lines)
